---
 - name: DB installations
   action: apt pkg={{ item }}
   tags: db
   with_items:
     - mysql-server
     - mysql-client
     - python-mysqldb

 - name: setup config file
   copy: src=config.cnf dest=/etc/mysql/my.cnf mode=0640
   notify: restart mysql

 - name: Create a new database
   mysql_db: name={{ database }} state=present