---
 - name: Install nodejs pre packages
   action: apt pkg={{ item }}
   tags: nodejs
   with_items:
     - python-software-properties
     - g++
     - make

 - name: Nodejs | Install ppa key
   apt_repository: repo=ppa:chris-lea/node.js state=present

 - name: Install nodejs
   apt: name=nodejs state=latest
